name: docker-push

on:
  workflow_dispatch:

  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:API"
          push: true
          tags: fabala/countmein:latest
  deploy:
    needs: docker
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  migrate:
    needs: docker
    name: Run database migrations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set up the .NET Core runtime and SDK
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.203

      # Restore dependencies and build the project
      - name: Restore and build
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore

      # Run Entity Framework Core migrations
      - name: Run EF Core Migrations
        run: |
          dotnet ef database update --project ../../API
        env:
          ASPNETCORE_ENVIRONMENT: Production
